# Generated by Django 6.0.6 on 2026-10-06 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Ration Kits'), ('WATER', 'Drinking Water & Purification'), ('MEDICAL', 'Medical Aid & First Aid Supplies'), ('SHELTER_SUPPLIES', 'Tents & Tarpaulins'), ('EQUIPMENT', 'Rescue Boats & Life Jackets'), ('CLOTHING', 'Blankets & Emergency Clothing')], db_index=True, max_length=30)),
                ('quantity_available', models.IntegerField(default=0)),
                ('unit', models.CharField(default='units', max_length=30)),
                ('storage_location', models.CharField(max_length=200)),
                ('district', models.CharField(default='Chennai', max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('responder_type', models.CharField(choices=[('NDRF', 'NDRF (National Disaster Response Force)'), ('SDRF', 'SDRF (State Disaster Response Force)'), ('FIRE_RESCUE', 'Tamil Nadu Fire & Rescue Services'), ('POLICE', 'Police Emergency Unit'), ('MEDICAL_EMS', '108 Emergency Medical Services'), ('VOLUNTEER', 'Trained Civil Defense Volunteer Group')], default='SDRF', max_length=30)),
                ('team_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('current_location_name', models.CharField(blank=True, default='Command Base', max_length=150)),
                ('status', models.CharField(choices=[('Available', 'Available on Standby'), ('Deployed', 'Deployed to Incident'), ('Off Duty', 'Off Duty')], db_index=True, default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manager_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('district', models.CharField(default='Chennai', max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_capacity', models.IntegerField(default=200)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('facilities_description', models.TextField(blank=True, help_text='e.g. Clean drinking water, food distribution, medical first aid counter, power backup')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Ration Kits'), ('WATER', 'Drinking Water & Purification'), ('MEDICAL', 'Medical Aid & First Aid Supplies'), ('SHELTER_SUPPLIES', 'Tents & Tarpaulins'), ('EQUIPMENT', 'Rescue Boats & Life Jackets'), ('CLOTHING', 'Blankets & Emergency Clothing')], db_index=True, max_length=30)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='units', max_length=30)),
                ('target_region', models.CharField(blank=True, default='General Relief / All Regions', max_length=150)),
                ('pickup_location', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Received', 'Received'), ('Allocated', 'Allocated'), ('Delivered', 'Delivered')], db_index=True, default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_to_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_donations', to='emergencies.emergencyrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hospital_type', models.CharField(default='District Emergency Center', max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('district', models.CharField(default='Chennai', max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_beds', models.IntegerField(default=100)),
                ('available_beds', models.IntegerField(default=20)),
                ('icu_beds_available', models.IntegerField(default=5)),
                ('oxygen_available_liters', models.IntegerField(default=500)),
                ('blood_units_available', models.IntegerField(default=30)),
                ('ambulances_available', models.IntegerField(default=2)),
                ('is_emergency_ready', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
