# Generated by Django 6.0.6 on 2026-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
                ('total_active_emergencies', models.IntegerField(default=0)),
                ('pending_emergencies', models.IntegerField(default=0)),
                ('resolved_emergencies', models.IntegerField(default=0)),
                ('avg_response_time_minutes', models.FloatField(blank=True, null=True)),
                ('total_donations_value', models.IntegerField(default=0)),
                ('shelter_utilization_pct', models.FloatField(default=0.0)),
                ('hospital_bed_occupancy_pct', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-snapshot_time'],
            },
        ),
    ]
