# Generated by Django 6.0.6 on 2026-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDACSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('EQ', 'Earthquake'), ('TC', 'Tropical Cyclone'), ('FL', 'Flood'), ('DR', 'Drought'), ('VO', 'Volcano'), ('WF', 'Wildfire'), ('TS', 'Tsunami'), ('OTHER', 'Other Disaster')], db_index=True, max_length=20)),
                ('event_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('iso3', models.CharField(blank=True, max_length=10)),
                ('affected_area', models.TextField(blank=True)),
                ('severity_level', models.CharField(blank=True, max_length=150)),
                ('alert_level', models.CharField(choices=[('Green', 'Green - Minor Impact'), ('Orange', 'Orange - Moderate Impact'), ('Red', 'Red - Severe / Catastrophic Impact')], db_index=True, default='Green', max_length=20)),
                ('alert_score', models.FloatField(default=1.0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('details_url', models.URLField(blank=True, max_length=500)),
                ('is_india', models.BooleanField(db_index=True, default=False)),
                ('is_tamil_nadu', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GDACS Event',
                'verbose_name_plural': 'GDACS Events',
                'ordering': ['-event_date', '-source_updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GDACSSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, max_length=20)),
                ('events_synced', models.IntegerField(default=0)),
                ('india_events_count', models.IntegerField(default=0)),
                ('tamil_nadu_events_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'GDACS Sync Log',
                'verbose_name_plural': 'GDACS Sync Logs',
                'ordering': ['-sync_time'],
            },
        ),
    ]
