# Generated by Django 6.0.6 on 2026-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('request_type', models.CharField(choices=[('EMERGENCY', 'Life Safety & Evacuation'), ('RESOURCE', 'Food, Water & Relief Supplies'), ('SHELTER', 'Emergency Shelter Placement'), ('MEDICAL', 'Urgent Medical Aid & Hospitalization')], db_index=True, default='EMERGENCY', max_length=20)),
                ('category', models.CharField(max_length=120)),
                ('quantity_needed', models.IntegerField(default=1)),
                ('unit', models.CharField(default='persons / units', max_length=30)),
                ('severity', models.IntegerField(choices=[(1, '1 - Low (Non-life threatening, minor assistance)'), (2, '2 - Medium (Moderate disruption, stable conditions)'), (3, '3 - High (Severe disruption, urgent supplies needed)'), (4, '4 - Critical (Immediate hazard, vulnerable individuals)'), (5, '5 - Catastrophic (Life-threatening emergency, trapped victims)')], db_index=True, default=3)),
                ('affected_people', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField()),
                ('district', models.CharField(blank=True, default='Chennai', max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Verified by Ops'), ('Assigned', 'Assigned to Responder'), ('Responding', 'Responder Responding'), ('Resolved', 'Resolved & Closed')], db_index=True, default='Pending', max_length=20)),
                ('priority_score', models.FloatField(db_index=True, default=0.0)),
                ('priority_classification', models.CharField(choices=[('Low', 'Low Priority'), ('Medium', 'Medium Priority'), ('High', 'High Priority'), ('Critical', 'Critical Priority')], db_index=True, default='Medium', max_length=20)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('responding_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_minutes', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
    ]
