# Generated by Django 6.0.6 on 2026-10-06 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencies', '0001_initial'),
        ('relief', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='assigned_responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emergencies', to='relief.responder'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
