# Generated by Django 6.0.6 on 2026-10-06 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('EMERGENCY', 'Emergency Alert'), ('STATUS_UPDATE', 'Request Status Update'), ('DONATION', 'Donation Pipeline'), ('GDACS', 'GDACS Regional Hazard'), ('SYSTEM', 'Operations Announcement')], default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
